[package]
name = "kizami-ingestion"
version = "0.1.0"
edition = "2021"

[dependencies]
kizami-shared = { path = "../shared" }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
